title: Vivek Basavanth Hanagoji
description: "I am a grad student at Northeastern University pursuing Master of Science in Information Systems specializing in Data Science and Analytics."

location: Boston, MA  
mobile: (+1) 617-368-0288  
email: hanagojivivek@gmail.com  
linkedin_url: https://www.linkedin.com/in/hanagojiv
logo: /assets/profile.jpg
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme # Add other plugins here if needed
